# Generated by Django 4.2.1 on 2023-06-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=11)),
                ('postcode', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=50)),
                ('account', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('roleID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.user')),
            ],
        ),
        migrations.CreateModel(
            name='HaveAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.user')),
            ],
        ),
        migrations.CreateModel(
            name='CounterSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.user')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.customer'),
        ),
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.user')),
            ],
        ),
    ]
