# Generated by Django 4.2.1 on 2023-06-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_user_roleid'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.file'),
            preserve_default=False,
        ),
    ]
