# Generated by Django 4.2.1 on 2023-06-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_remove_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contract.file'),
            preserve_default=False,
        ),
    ]
