# Generated by Django 4.2.1 on 2023-06-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='contract.user'),
            preserve_default=False,
        ),
    ]
