# Generated by Django 4.2.1 on 2023-06-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_contract_state_contract_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
