# Generated by Django 4.2.1 on 2023-06-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='distribute',
            field=models.IntegerField(default=0),
        ),
    ]
