# Generated by Django 4.2.1 on 2023-06-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_distribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='approve',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='approve',
            name='judge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='countersign',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sign',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
