# Generated by Django 4.2.1 on 2023-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_alter_customer_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleID',
            field=models.IntegerField(default=1),
        ),
    ]
